version: '3.6'

networks:
  app-network:
    driver: bridge
    external: true
    name: app-network

services:
  zk1:
    env_file: ['./.env' ]
    image: zookeeper:3.4.14
    restart: always
    container_name: zk1
    hostname: zk1
    ports:
    - "2181:2181"
    volumes:
    - ${ZK_ROOT_DIR}/zk1/conf/zoo.cfg:/opt/zookeeper-3.4.13/conf/zoo.cfg
    - ${ZK_ROOT_DIR}/zk1/data:/data
    - ${ZK_ROOT_DIR}/zk1/log:/datalog
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zk1:2888:3888 server.2=zk2:2888:3888 server.3=zk3:2888:3888
    networks:
      app-network:
        ipv4_address: 192.168.100.2
 
  zk2:
    env_file: ['./.env' ]
    image: zookeeper:3.4.14
    restart: always
    container_name: zk2
    hostname: zk2
    ports:
    - "2182:2181"
    volumes:
    - ${ZK_ROOT_DIR}/zk2/conf/zoo.cfg:/opt/zookeeper-3.4.13/conf/zoo.cfg
    - ${ZK_ROOT_DIR}/zk2/data:/data
    - ${ZK_ROOT_DIR}/zk2/log:/datalog
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zk1:2888:3888 server.2=zk2:2888:3888 server.3=zk3:2888:3888
    networks:
      app-network:
        ipv4_address: 192.168.100.3
 
  zk3:
    env_file: ['./.env' ]
    image: zookeeper:3.4.14
    restart: always
    container_name: zk3
    hostname: zk3
    ports:
    - "2183:2181"
    volumes:
    - ${ZK_ROOT_DIR}/zk3/conf/zoo.cfg:/opt/zookeeper-3.4.13/conf/zoo.cfg
    - ${ZK_ROOT_DIR}/zk3/data:/data
    - ${ZK_ROOT_DIR}/zk3/log:/datalog
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zk1:2888:3888 server.2=zk2:2888:3888 server.3=zk3:2888:3888
    networks:
      app-network:
        ipv4_address: 192.168.100.4